add ssh config files

diff --git a/config/dotfiles/dotbot.yaml b/config/dotfiles/dotbot.yaml
--- a/config/dotfiles/dotbot.yaml
+++ b/config/dotfiles/dotbot.yaml
@@ -24,6 +24,9 @@
     ~/.local/bin/:
         glob: true
         path: bin/*
+    ~/.ssh/:
+        glob: true
+        path: config/ssh/*
 
     # Alfred
     ~/Library/ApplicationSupport/Alfred/prefs.json:
@@ -64,6 +67,19 @@
         # see: https://gist.github.com/cowboy/3118588
         while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
 
+    - description: Checking PGP Key
+      command: |-
+        KEYNAME='B5C5503F193E8ADE58FB0B643CB59A7906ADEEF8'
+        if ! gpg -K $KEYNAME &>/dev/null; then
+          echo "Getting key from secrethub"
+          KEY="$(secrethub read wren/dotfiles/gpg/private.key)"
+          echo "Loading key into GPG."
+          gpg-connect-agent killagent /bye
+          echo "$KEY" | gpg --import
+          echo "Setting trust on key."
+          expect -c "spawn gpg --edit-key $KEYNAME trust quit; send \"5\ry\r\"; expect eof"
+        fi
+
     - description: Installing apps via Homebrew
       command: |-
         BREWFILE="$DOTFILES_DIR/config/dotfiles/Brewfile"
@@ -100,8 +116,20 @@
           sh ./config/dotfiles/macos.sh
         fi
 
+    - description: Decrypt files
+      command: |-
+        if ! gpg -K B5C5503F193E8ADE58FB0B643CB59A7906ADEEF8 &>/dev/null; then
+          printf "$UNDERLINE$(tput setaf 1)ERROR:$(tput sgr0) "
+          printf "GPG key not available.\n"
+          exit 1
+        fi
+        for file in ./config/ssh/configs_encrypted/*; do
+          echo " - decrypting ${file}"
+          sops -d "$file" > "./config/ssh/configs/${file:t}"
+        done
 
 - pipx:
     file: config/dotfiles/pipx.txt
     stdout: false
     stderr: true
+
